export const countries = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Ivory Coast",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Republic of the Congo",
  "Rwanda",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
];

export const africanLanguages = [
  "Swahili",
  "Amharic",
  "Yoruba",
  "Zulu",
  "Hausa",
  "Arabic",
  "Igbo",
  "Shona",
  "Xhosa",
  "Somali",
  "Berber",
  "Oromo",
  "Wolof",
  "Fulani (Fula)",
  "Tswana",
  "Lingala",
  "Kikuyu",
  "Kinyarwanda",
  "Chichewa",
  "Sesotho",
  "Tigrinya",
  "Bambara",
  "Luganda",
  "Akan (Twi/Fante)",
  "Sango",
];

export const musicInterestList = [
  "Amapiano",
  "Afro beats",
  "Hip Hop",
  "R&B",
  "Pop",
  "House",
  "Jazz",
  "Reggae",
  "Dancehall",
  "Soca",
  "Kwaito",
  "Afro house",
  "Trap",
  "Drill",
  "EDM",
  "K-Pop",
  "Latin",
  "Afro jazz",
  "Soul",
];

export const foodInterestList = [
  "Jollof Rice",
  "Fufu",
  "Pounded Yam",
  "Egusi Soup",
  "Suya",
  "Bunny Chow",
  "Samosa",
  "Biryani",
  "Plantain",
  "Mandazi",
  "Moi Moi",
  "Chicken",
];

export const communityGuidelines = [
  "To ensure the best experience, we ask that you follow our community guidelines.",
  "Create an authentic profile",
  "Be sure to use your authentic photos, name, age, and other profile details",
  "Be respectful towards other members",
  "Use appropriate language and be mindful of other people's feelings and opinions",
  "Keep it clean",
  "Refrain from solicitation and from posting explicit content on your profile or in chats",
  "Don't share your phone number or personal information with your matches until you feel comfortable doing so",
  "We hope you will find someone who will truly share a bowl of jollof.",
];

export const diasporaInvolvementList = [
  "Youth Empowerment",
  "Social Entrepreneurship in Africa",
  "African Fintech Innovations",
  "African Wildlife Conservation",
  "Renewable Energy Initiatives",
  "Community & Social Activities",
  "Volunteering with African NGOs",
  "Human Rights Activism",
  "Clean Water Initiatives",
  "Pan-Africanism Movements",
];

export const ethnicBackgrounds = [
  "Akan",
  "Amhara",
  "Ashanti",
  "Bantu",
  "Berber",
  "Chewa",
  "Chokwe",
  "Dinka",
  "Edo",
  "Ewe",
  "Fula",
  "Ganda",
  "Hausa",
  "Herero",
  "Igbo",
  "Kikuyu",
  "Kongo",
  "Luba",
  "Luo",
  "Maasai",
  "Mandinka",
  "Ndebele",
  "Nilotic",
  "Oromo",
  "Shona",
  "Somali",
  "Sotho",
  "Swahili",
  "Tigray",
  "Tswana",
  "Tuareg",
  "Wolof",
  "Xhosa",
  "Yoruba",
  "Zulu",
];

export const starSigns = [
  "Aquarius",
  "Aries",
  "Cancer",
  "Capricorn",
  "Gemini",
  "Leo",
  "Libra",
  "Pisces",
  "Sagittarius",
  "Scorpio",
  "Taurus",
  "Virgo",
];

export const educationLevels = [
  "PhD",
  "MBA",
  "Msc",
  "Bsc",
  "High School Degree",
];

export const childrenPreference = [
  "No Children",
  "1 Child",
  "2 Children",
  "3 Children",
  "4 Children",
  "5 & More",
];

export const religionPreference = [
  "Christian",
  "Catholic",
  "Islam",
  "Hindu",
  "Agnostic",
];
